# Criar um contêiner
# https://medium.com/zabbix-brasil/monitorando-docker-com-zabbix-5-e-zabbix-agent2-1a9a8d53fbd3
# docker compose -f docker-compose.yml up --build -d --no-recreate

version: '3.9'

services:
  zabbix-mysql:
    container_name: zabbix-mysql
    hostname: zabbix-mysql
    image: mysql:${MYSQL_TAG:-latest}
    restart: unless-stopped
    # ports:
    #   - "3306:3306"
    volumes:
      - /usr/local/docker/zabbix/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zabbix}
      MYSQL_USER: ${MYSQL_USER:-zabbix}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-zabbix}
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_bin"
    # networks:
    #   - network-monitor
    networks:
      network-monitor:
        ipv4_address: 10.0.0.2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zabbix-snmptraps:
    container_name: zabbix-snmptraps
    hostname: zabbix-snmptraps
    image: zabbix/zabbix-snmptraps:${ZB_TAG_TRAPS:-latest}
    restart: unless-stopped
    # ports:
    #   - "162:1162/udp"
    volumes:
      - /usr/local/docker/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /usr/local/docker/zabbix/mibs:/usr/share/snmp/mibs:ro
  #   networks:
  #     - network-monitor
    networks:
      network-monitor:
        ipv4_address: 10.0.0.3

  zabbix-server:
    container_name: zabbix-server
    hostname: zabbix-server
    image: zabbix/zabbix-server-mysql:${ZB_TAG_SRV:-latest}
    #restart: unless-stopped
    #    ports:
    #       - "10050:10050"
    #       - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-mysql
      DB_SERVER_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zabbix}
      MYSQL_USER: ${MYSQL_USER:-zabbix}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-zabbix}
      ZBX_ENABLE_SNMP_TRAPS: "true"
      ZBX_STARTPOLLERS: 5
      ZBX_STARTPINGERS: 1
      ZBX_LISTENPORT: 10051
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_PROBLEMHOUSEKEEPINGFREQUENCY: 60
      ZBX_SENDERFREQUENCY: 30
      ZBX_CACHEUPDATEFREQUENCY: 10
      ZBX_STARTDBSYNCERS: 4
      ZBX_EXPORTFILESIZE: 1G
      ZBX_HISTORYCACHESIZE: 16M
      ZBX_HISTORYINDEXCACHESIZE: 4M
      ZBX_HISTORYSTORAGEDATEINDEX: 0
      ZBX_TRENDCACHESIZE: 4M
      ZBX_TRENDFUNCTIONCACHESIZE: 4M
      ZBX_VALUECACHESIZE: 8M
      ZBX_UNREACHABLEPERIOD: 45
      ZBX_UNAVAILABLEDELAY: 60
      ZBX_UNREACHABLEDELAY: 15
      ZBX_LOGSLOWQUERIES: 3000
    # networks:
    #   - network-monitor
    networks:
      network-monitor:
        ipv4_address: 10.0.0.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /usr/local/docker/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /usr/local/docker/zabbix/extrnalscripts:/usr/lib/zabbix/externalscripts:ro
      - /usr/local/docker/zabbix/modules:/var/lib/zabbix/modules:ro
      - /usr/local/docker/zabbix/enc:/var/lib/zabbix/enc:ro
      - /usr/local/docker/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /usr/local/docker/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - /usr/local/docker/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
      - /usr/local/docker/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs:ro
      - /usr/local/docker/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys:ro
    volumes_from:
      - zabbix-snmptraps
    depends_on:
      - zabbix-mysql
      - zabbix-snmptraps
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: "1"
          memory: 1280M
        reservations:
          memory: 768M
          cpus: "0.5"

  zabbix-frontend:
    container_name: zabbix-frontend
    hostname: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql:${ZB_TAG_FRONT:-latest}
    restart: unless-stopped
    ports:
      - "8088:8080"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-mysql
      DB_SERVER_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zabbix}
      MYSQL_USER: ${MYSQL_USER:-zabbix}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-zabbix}
      PHP_TZ: "America/Caracas"
      ZBX_POSTMAXSIZE: 64M
      ZBX_MAXEXECUTIONTIME: 500
    # networks:
    #   - network-monitor
    networks:
      network-monitor:
        ipv4_address: 10.0.0.5
    depends_on:
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    hostname: zabbix-agent
    image: zabbix/zabbix-agent2:${ZB_TAG_FRONT:-latest}
    #image: zabbix/zabbix-agent:${ZB_TAG_FRONT:-latest}
    restart: unless-stopped
    privileged: true
    # networks:
    #   - network-monitor
    networks:
      network-monitor:
        ipv4_address: 10.0.0.6
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run:/var/run:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /usr/local/docker/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - /usr/local/docker/zabbix/zabbix_agent2.d/zabbix_agent2.conf:/etc/zabbix/zabbix_agent2.d/zabbix_agent2.conf:ro
      - /usr/local/docker/zabbix/modules:/var/lib/zabbix/modules:ro
      - /usr/local/docker/zabbix/enc:/var/lib/zabbix/enc:ro
      - /usr/local/docker/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    # command:
    #   - "--add-host=host.docker.internal:host-gateway"
    links:
      - zabbix-server
    depends_on:
      - zabbix-server

  zabbix-grafana:
    container_name: zabbix-grafana
    hostname: zabbix-grafana
    image: grafana/grafana:${TAG_GF:-latest}
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-12345678}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL:-http://localhost:8089}
      GF_INSTALL_PLUGINS: ${GF_INSTALL_PLUGINS:-alexanderzobnin-zabbix-app}
    ports:
      - "8089:3000"
    # depends_on:
    #   - zabbix-prometheus
    # networks:
    #   - network-monitor
    networks:
      network-monitor:
        ipv4_address: 10.0.0.7
    volumes:
      - /usr/local/docker/grafana_storage:/var/lib/grafana:rw
    user: "0"
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: "1"
          memory: 768M
        reservations:
          memory: 512M
          cpus: "0.5"

  # zabbix-prometheus:
  #   container_name: zabbix-prometheus
  #   hostname: zabbix-prometheus
  #   image: prom/prometheus:latest
  #   volumes:
  #     - /usr/local/docker/prometheus/etc:/etc/prometheus:rw
  #     - /usr/local/docker/prometheus/data:/prometheus:rw
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   networks:
  #     - network-monitor
  #   ports:
  #     - 9090:9090
  #    networks:
  #      network-monitor:
  #        ipv4_address: 10.0.0.8
  #   links:
  #     - zabbix-cadvisor
  #     - zabbix-alert-manager
  #   depends_on:
  #     - zabbix-cadvisor

  # zabbix-node-exporter:
  #   container_name: zabbix-node-exporter
  #   hostname: zabbix-node-exporter
  #   image: prom/node-exporter:latest
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #     - /:/host:ro,rslave
  #   command:
  #     - '--path.rootfs=/host'
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - --collector.filesystem.ignored-mount-points
  #     - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  #   networks:
  #     - network-monitor
  #   ports:
  #     - 9100:9100
  #    networks:
  #      network-monitor:
  #        ipv4_address: 10.0.0.9

  # zabbix-alert-manager:
  #   container_name: zabbix-alert-manager
  #   hostname: zabbix-alert-manager
  #   image: prom/alertmanager:latest
  #   volumes:
  #     - /usr/local/docker/alertmanager:/alertmanager:rw
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  #   networks:
  #     - network-monitor
  #   ports:
  #     - 9093:9093
  #    networks:
  #      network-monitor:
  #        ipv4_address: 10.0.0.10

  # zabbix-cadvisor:
  #   container_name: zabbix-cadvisor
  #   hostname: zabbix-cadvisor
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - 9080:8080
  #   networks:
  #     - network-monitor
  #   restart: unless-stopped
  #    networks:
  #      network-monitor:
  #        ipv4_address: 10.0.0.11

networks:
  network-monitor:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
