global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'monitoring'

rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['prometheus:9090']
    basic_auth:
      username: "admin"
      password: "12345678"
    # Relabeling "instance" to remove the ":9100" part
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    scheme: http
    static_configs:
         - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    scheme: http
    static_configs:
          - targets: ['cadvisor:8080']
    relabel_configs:
          - separator: ;
            regex: (.*)
            target_label: instance
            replacement: cadvisor
            action: replace


  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    scheme: http
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 5s
    static_configs:
         - targets: ['netdata:19999']
